// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffidhopvzfplngrjqzrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmaWRob3B2emZwbG5ncmpxenJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzk1NTEsImV4cCI6MjA3MjY1NTU1MX0.x9O5GGD_yoW9U6lFPSp3sskLOkx-S7P1CN7eyLXXAdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});